SAMPLE_RECEIPTS = {
    "sample-001": {
        "merchant": "Delta Air Lines",
        "date": "2026-02-15",
        "amount": 487.50,
        "currency": "USD",
        "suggested_category": "Travel",
        "field_confidence": {
            "merchant": "High",
            "date": "High",
            "amount": "High",
            "category": "High",
        },
        "description": "Flight confirmation receipt LAX to JFK",
        "line_items": [
            {"name": "Economy Ticket LAX-JFK", "quantity": 1, "unit_price": 425.00},
            {"name": "Seat Selection (12A)", "quantity": 1, "unit_price": 35.00},
        ],
        "subtotal": 460.00,
        "tax_amount": 27.50,
    },
    "sample-002": {
        "merchant": "The Capital Grille",
        "date": "2026-02-18",
        "amount": 156.32,
        "currency": "USD",
        "suggested_category": "Meals & Entertainment",
        "field_confidence": {
            "merchant": "High",
            "date": "Medium",
            "amount": "High",
            "category": "High",
        },
        "description": "Restaurant dinner receipt for 3 guests",
        "line_items": [
            {"name": "Dry-Aged NY Strip", "quantity": 2, "unit_price": 42.00},
            {"name": "Lobster Bisque", "quantity": 1, "unit_price": 18.00},
            {"name": "Caesar Salad", "quantity": 1, "unit_price": 14.00},
            {"name": "Wine (Glass)", "quantity": 3, "unit_price": 9.00},
        ],
        "subtotal": 143.00,
        "tax_amount": 13.32,
    },
    "sample-003": {
        "merchant": "Staples",
        "date": "2026-02-20",
        "amount": 89.97,
        "currency": "USD",
        "suggested_category": "Office Supplies",
        "field_confidence": {
            "merchant": "High",
            "date": "High",
            "amount": "Medium",
            "category": "Medium",
        },
        "description": "Office supplies - printer paper, toner, pens",
        "line_items": [
            {"name": "Printer Paper (5-ream)", "quantity": 1, "unit_price": 34.99},
            {"name": "HP Toner Cartridge", "quantity": 1, "unit_price": 42.99},
            {"name": "Ballpoint Pens (12-pack)", "quantity": 1, "unit_price": 5.49},
        ],
        "subtotal": 83.47,
        "tax_amount": 6.50,
    },
    "sample-004": {
        "merchant": "Marriott Downtown",
        "date": "2026-02-21",
        "amount": 312.00,
        "currency": "USD",
        "suggested_category": "Accommodation",
        "field_confidence": {
            "merchant": "High",
            "date": "High",
            "amount": "High",
            "category": "High",
        },
        "description": "Hotel stay 2 nights business trip",
        "line_items": [
            {"name": "Standard Room", "quantity": 2, "unit_price": 139.00},
            {"name": "Resort Fee", "quantity": 2, "unit_price": 7.50},
        ],
        "subtotal": 293.00,
        "tax_amount": 19.00,
    },
    "sample-005": {
        "merchant": "Uber",
        "date": "2026-02-22",
        "amount": 34.75,
        "currency": "USD",
        "suggested_category": "Transportation",
        "field_confidence": {
            "merchant": "High",
            "date": "High",
            "amount": "High",
            "category": "Medium",
        },
        "description": "Ride from airport to hotel",
        "line_items": [
            {"name": "UberX Ride (Airport to Hotel)", "quantity": 1, "unit_price": 28.50},
            {"name": "Airport Surcharge", "quantity": 1, "unit_price": 3.50},
        ],
        "subtotal": 32.00,
        "tax_amount": 2.75,
    },
}
